### ISSUE TITLE
Error while running tracker2vis.py

### ISSUE THREAD

**Issue by codepujan** [hhromic/dynamic-community-vis#1]
I tried cloning this wonderful library and getting the code up and running: without any modifications , but the tracker2vis.py to generate example.timeline.json is giving me error as : 

`python3 python/tracker2vis.py --timeline example/example.timeline --output example/example.timeline.json --events example/example.events.json
Traceback (most recent call last):
  File "python/tracker2vis.py", line 64, in <module>
    main()
  File "python/tracker2vis.py", line 46, in main
    expansions = timeline.find_expansions(step_communities, args.expansion_threshold)
  File "/Users/pujanpaudel/Desktop/FallTwitter/DynamicCommunity/Test/dynamic-community-vis/python/helpers/timeline.py", line 169, in find_expansions
    c_i = step_communities[s_i.number][s_i.community]
KeyError: 1`

**Comment by hhromic** [comment]
Hi, thanks for the kind words. The problem is that by default the script is looking for the step files (`00001.comm`, `00002.comm`, ...) in the same directory that you are running the script.
Because you run the script from the top-directory it is not finding the files inside the `example` directory. The solution is simple, just use the `--steps-dir` parameter like this:

    python3 python/tracker2vis.py \
      --steps-dir example \
      --timeline example/example.timeline \
      --output example/example.timeline.json \
      --events example/example.events.json
